index:
   path: /
   controller: App\Controller\DefaultController::index

doc:
   path: /documentation
   controller: App\Controller\DefaultController::documentation

list_authors:
   path: /author
   controller: App\Controller\AuthorController::index
